import "./Skills.css";

const Skills = () => {
  return (
    <>
      <div className="skillSection">
        <h1>My Skills</h1>
        <div className="skill-logos">
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/color/144/000000/c-programming.png"
            alt="c-programming"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/?size=100&id=Fycm8TUhWmFU&format=png&color=000000"
            alt="csharp"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/color/144/000000/c-plus-plus-logo.png"
            alt="cplusplus"
          />
          <img
            width="120"
            height="120"
            src="https://img.icons8.com/external-tal-revivo-color-tal-revivo/96/000000/external-react-a-javascript-library-for-building-user-interfaces-logo-color-tal-revivo.png"
            alt="external-react-a-javascript-library-for-building-user-interfaces-logo-color-tal-revivo"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/?size=100&id=yUdJlcKanVbh&format=png&color=000000"
            alt="nextjs"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/?size=100&id=74402&format=png&color=000000"
            alt="mongodb"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/?size=100&id=sH0rW2TvYdr9&format=png&color=000000"
            alt="supabase"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/?size=100&id=38561&format=png&color=000000"
            alt="postgressql"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/color/144/000000/javascript--v1.png"
            alt="javascript--v1"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/color/144/typescript.png"
            alt="typescript"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/color/144/000000/tailwindcss.png"
            alt="tailwindcss"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/color/144/000000/bootstrap--v2.png"
            alt="bootstrap--v2"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/color/144/python--v1.png"
            alt="python--v1"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/?size=100&id=39292&format=png&color=000000"
            alt="jenkins"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/color/144/000000/git.png"
            alt="git"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/?size=100&id=TLI9oiMzpREF&format=png&color=000000"
            alt="selenium"
          />
          <img
            width="144"
            height="144"
            src="https://img.icons8.com/?size=100&id=ggvujvXlC5MA&format=png&color=000000"
            alt="testrails"
          />
          <img
            width="144"
            height="144"
            src="https://raw.githubusercontent.com/mrdoob/three.js/38bf5f47a8c01a1d12d16a41b4097dc9ee31daad/files/icon.svg"
            alt="threejs"
          />
        </div>
      </div>
    </>
  );
};

export default Skills;
